### PR TITLE
Updated to nodemon ~1.3.0

### LINKED ISSUE #46: Watching too many files - this might cause high cpu usage
Hi,

I have just updated to 0.3.0 and I started getting following error in the console: 

> [nodemon] watching 32,903 files - this might cause high cpu usage. To reduce use "--watch".

I do have `watch` configured: 

    options: {
        watch: ['backend', 'conf/app'],

So I don't know whether it was always broken without warning, or it is broken now with the upgrade.

### PR DESCRIPTION
**Pull request by arty-name**
Fixes #46

### CODE REVIEW

**Comment by arty-name** [comment]
Looks like something is wrong with the testing environment itself, even `npm install` has failed there

**Comment by abiyasa** [comment]
I did `npm info nodemon`, unfortunately they only have 1.2.1 as the latest, not yet 1.3.0. 
The 1.3.0-x is only available for debug or dev version, which you can install by using nodemon@dev or nodemon@debug

**Comment by arty-name** [comment]
that's weird: exactly same version bump on my local computer didn't cause any errors, and I don't use dev or debug

**Comment by abiyasa** [comment]
I did `npm install` using package.json defined on your [fix](https://github.com/arty-name/grunt-nodemon/commit/d4b60d253d7d7b43aae4a8a5e742795797744031) but I always got nodemon@1.2.1 installed. I tried to npm cache clean and npm install but still got v1.2.1 instead of 1.3.0.

**Comment by arty-name** [comment]
I see, maybe I didn't pay enough attention. Well, this upgrade will happen anyway, when non-dev version of nodemon is released, so I'll just keep this PR around :)

**Comment by abiyasa** [comment]
Yup, we just have to wait until nodemon release their v1.3.0 to npm registry :-)

**Comment by jdoose** [comment]
I am new to this, but on the nodemon github site it states that 1.3.0-1 was released (https://github.com/remy/nodemon/releases). Maybe it is just the format in the package.json in grunt-nodemon that is wrong? it works if I change it to 
"nodemon": "~1.3.0-0"

Or is it a convention that 1.3.0-x releases are not stable/official ones?

**Comment by abiyasa** [comment]
@jdoose According to semver (http://semver.org/spec/v1.0.0.html), the dash means pre-release.
This means 1.3.0-1 < 1.3.0

**Comment by jdoose** [comment]
@abiyasa ok, thanks for clarification! Too bad. :/

**Comment by abiyasa** [comment]
nodemon v1.3.0 has been released 2 days ago. The latest release version is v1.3.2. I guess it's time to merge this?

**Comment by khaledabbas** [comment]
pls merge..

**Comment by ChrisWren** [comment]
Sorry for the delay.

**Comment by abiyasa** [comment]
Thanks for the update :thumbsup:

**Comment by jdoose** [comment]
Thanks for the update!

**Pull request merged**
